// emoji-data.js

// Recherche Bilingue (FR/EN) - Teintes jaunes uniquement
const EMOJI_LIST = [
// --- LE TOP 10 (ORDRE STRICT) ---
{ char: "😂", keywords: "laugh tears joy lol rire larmes joie heureux" },
{ char: "❤️", keywords: "love heart red passion amour coeur rouge passion" },
{ char: "🤣", keywords: "rofl laugh floor funny rire rouler drole mdr" },
{ char: "👍", keywords: "ok yes good thumbs up daccord oui bien pouce" },
{ char: "😭", keywords: "cry sad tears upset pleurer triste larmes degoute" },
{ char: "🙏", keywords: "please pray thanks hope svp merci prier espoir" },
{ char: "😘", keywords: "kiss love heart smooch bisou amour coeur embrasser" },
{ char: "🥰", keywords: "love hearts adore sweet amour coeurs adore mignon" },
{ char: "😍", keywords: "love eyes heart crush amour yeux coeur kiffe" },
{ char: "😊", keywords: "smile happy shy cute sourire heureux timide mignon" },

// --- TOP 100 & UTILES ---
{ char: "🔥", keywords: "fire hot flame lit feu chaud flamme genial" },
{ char: "✨", keywords: "stars sparkle shiny magic etoiles brillant magique" },
{ char: "🤔", keywords: "think hmm doubt ponder pense reflexion doute" },
{ char: "😎", keywords: "cool sun glasses style lunettes soleil stylé" },
{ char: "🚀", keywords: "rocket space moon launch fusee espace lune lancer" },
{ char: "🎉", keywords: "party celebrate bravo win fete celebration bravo" },
{ char: "😢", keywords: "sad cry tear unhappy triste pleure larme malheur" },
{ char: "🔒", keywords: "lock private secret secure cadenas prive secret securite" },
{ char: "🔑", keywords: "key unlock access password cle ouvrir acces motdepasse" },
{ char: "🛡️", keywords: "shield protect guard security bouclier protection garde" },
{ char: "✅", keywords: "check ok done valid valide ok fait valider" },
{ char: "❌", keywords: "cross no error wrong croix non erreur faux" },
{ char: "⚠️", keywords: "warning danger alert attention danger alerte" },
{ char: "💡", keywords: "idea light bulb smart idee lumiere ampoule intelligent" },
{ char: "🌍", keywords: "earth world planet globe terre monde planete globe" },
{ char: "📱", keywords: "phone mobile smartphone tel telephone mobile" },
{ char: "💬", keywords: "chat bubble message speak bulle message parler" },
{ char: "💻", keywords: "computer laptop tech ordi ordinateur portable informatique" },
{ char: "⚙️", keywords: "gear settings tool rouage parametres outil" },
{ char: "🌈", keywords: "rainbow color sky arcenciel couleur ciel" },
{ char: "🍕", keywords: "pizza food hungry miam pizza nourriture faim" },
{ char: "☕", keywords: "coffee tea drink cafe the boisson" },
{ char: "⏳", keywords: "time wait sand timer temps attente sablier" },
{ char: "💪", keywords: "strong power muscle force fort muscle" },
{ char: "👀", keywords: "eyes look watch eyes yeux regarde voir" },
{ char: "🤩", keywords: "star wow amazing etoile impressionne incroyable" },
{ char: "🙄", keywords: "roll eyes bored whatever yeux blasé ennui" },
{ char: "🤤", keywords: "drool yum delicious bave miam delicieux" },
{ char: "😋", keywords: "yum tasty delicious miam bon delicieux" },
{ char: "😴", keywords: "sleep tired zzz dodo dormir fatigue" },
{ char: "🤮", keywords: "sick puke vomit malade vomi degout" },
{ char: "🤯", keywords: "mind blown shock explosion choqué incroyable" },
{ char: "🥳", keywords: "party celebrate happy fete celebration heureux" },
{ char: "😇", keywords: "angel innocent halo ange innocent saint" },
{ char: "🤠", keywords: "cowboy hat west cowboy chapeau ouest" },
{ char: "🤡", keywords: "clown funny scary clown drole peur" },
{ char: "🤥", keywords: "lie pinocchio nose mensonge menteur nez" },
{ char: "🤫", keywords: "quiet shh secret chut silence secret" },
{ char: "🧐", keywords: "monocle investigate smart monocle enquête intelligent" },
{ char: "🤓", keywords: "nerd geek smart intello geek intelligent" },
{ char: "👾", keywords: "alien game retro monstre jeu video" },
{ char: "🤖", keywords: "robot bot tech robot bot technique" },
{ char: "💩", keywords: "poop funny smile caca drole sourire" },
{ char: "👻", keywords: "ghost scary boo fantome peur bouh" },
{ char: "💀", keywords: "skull dead death crane mort deces" },
{ char: "👽", keywords: "alien ufo space extraterrestre ovni espace" },
{ char: "🎃", keywords: "halloween pumpkin citrouille halloween" },
{ char: "🌟", keywords: "star glow shining etoile brillant" },
{ char: "💥", keywords: "boom bang explosion choc explosion" },
{ char: "💦", keywords: "water drops sweat eau gouttes sueur" },
{ char: "💨", keywords: "wind fast run vent rapide courir" },
{ char: "💫", keywords: "dizzy star magic etourdi etoile magie" },
{ char: "💤", keywords: "sleep zzz tired dodo dormir fatigue" },
{ char: "💯", keywords: "hundred perfect score cent parfait score" },
{ char: "💢", keywords: "angry mad anger enervé colere" },
{ char: "💭", keywords: "thought dream cloud pensee reve nuage" },
{ char: "✉️", keywords: "mail letter email courrier lettre email" },
{ char: "📢", keywords: "speaker news announce hautparleur annonce" },
{ char: "🔔", keywords: "bell alert notice cloche alerte notification" },
{ char: "🎵", keywords: "music note song musique note chanson" },
{ char: "📸", keywords: "camera photo snap appareil photo" },
{ char: "🎮", keywords: "game play console jeu jouer console" },
{ char: "🎲", keywords: "dice game luck de jeu chance" },
{ char: "🎯", keywords: "target goal hit cible but reussite" },
{ char: "🛸", keywords: "ufo alien space ovni extraterrestre espace" },
{ char: "🚁", keywords: "helicopter air fly helicoptere air voler" },
{ char: "🚗", keywords: "car drive travel voiture conduire voyage" },
{ char: "🚲", keywords: "bike cycle bicycle velo cyclisme" },
{ char: "🏠", keywords: "home house building maison domicile batiment" },
{ char: "🏢", keywords: "office building work bureau batiment travail" },
{ char: "🏖️", keywords: "beach sand summer plage sable ete" },
{ char: "🌋", keywords: "volcano fire hot volcan feu chaud" },
{ char: "🍎", keywords: "apple fruit red pomme fruit rouge" },
{ char: "🍔", keywords: "burger food fastfood burger nourriture" },
{ char: "🍺", keywords: "beer drink alcohol biere boisson alcool" },
{ char: "🍦", keywords: "ice cream sweet glace sucre" },
{ char: "🎂", keywords: "cake birthday party gateau anniversaire fete" },
{ char: "🎈", keywords: "balloon party celebrate ballon fete celebrer" },
{ char: "🎁", keywords: "gift present surprise cadeau present surprise" },
{ char: "🏆", keywords: "trophy win winner trophee victoire gagnant" },
{ char: "🥇", keywords: "gold medal first medaille or premier" },
{ char: "🥈", keywords: "silver medal second medaille argent deuxieme" },
{ char: "🥉", keywords: "bronze medal third medaille bronze troisieme" },
{ char: "💼", keywords: "briefcase work business mallette travail affaire" },
{ char: "📌", keywords: "pin mark note punaise marquer note" },
{ char: "📍", keywords: "location map pin localisation carte epingle" },
{ char: "🔍", keywords: "search find look loupe chercher trouver" },
{ char: "💰", keywords: "money cash rich argent monnaie riche" },
{ char: "💎", keywords: "diamond gem jewel diamant gemme bijou" },

// --- FRANCE & SYMBOLES NATIONAUX ---
{ char: "🇫🇷", keywords: "france flag paris french drapeau paris francais patrie" },
{ char: "🥖", keywords: "baguette bread food french pain nourriture francais boulangerie" },
{ char: "🥐", keywords: "croissant bread breakfast french viennoiserie petitdejeuner francais" },
{ char: "🧀", keywords: "cheese food dairy french fromage nourriture laitage francais" },
{ char: "🍷", keywords: "wine drink alcohol french vin boisson alcool francais" },
{ char: "🐓", keywords: "rooster bird farm france coq oiseau ferme emblem" },
{ char: "🗼", keywords: "tower eiffel paris france tour paris monument" },
{ char: "🏰", keywords: "castle palace history france chateau palais histoire monument" },
{ char: "🍾", keywords: "champagne drink celebrate party champagne boisson fete feter" },

// --- RELIGION ---
{ char: "⛪", keywords: "church religion god pray eglise dieu prier chretien catholic" },
{ char: "✝️", keywords: "cross religion jesus christ croix jesus chretien catholic" },
{ char: "📿", keywords: "rosary prayer beads religion chapelet priere perles catholic" },
{ char: "🕯️", keywords: "candle light fire pray bougie lumiere feu priere catholic" },
{ char: "👼", keywords: "angel baby heaven holy ange bebe ciel saint catholic" },
{ char: "🕊️", keywords: "dove peace bird holy colombe paix oiseau saint" },
{ char: "👐", keywords: "open hands pray worship mains ouvertes priere culte" },

// --- ANIMAUX ---
{ char: "🐱", keywords: "cat kitten animal pet chat chaton mimi miaou" },
{ char: "🦝", keywords: "raccoon animal forest night raton laveur animal foret nuit" },
{ char: "🐔", keywords: "chicken hen bird farm poule poulet oiseau ferme" },
{ char: "🐿️", keywords: "squirrel animal nut forest ecureuil animal noisette foret" },
{ char: "🦄", keywords: "unicorn magic fantasy horse licorne magie feerique cheval" }
];
